# Generated by Django 3.2 on 2021-04-19 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_game', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='basicquiz',
            old_name='option1',
            new_name='good',
        ),
    ]
